# 导入数据

In [2]:
import pandas as pd
import os
from  pathlib import Path
train_file=r"zhengqi_train.txt"
test_file=r"zhengqi_test.txt"
data_dir=r"D:\project\tianchi\steam_prodict"
"""Path(data_dir,train_file)"""
table= pd.read_table(Path(data_dir,train_file))
table
# table=pd.read_excel(,
#                          sheet_name=0 , skiprows=2,
#                          names=["a","b","c"], usecols="A:M")

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V29,V30,V31,V32,V33,V34,V35,V36,V37,target
0,0.566,0.016,-0.143,0.407,0.452,-0.901,-1.812,-2.360,-0.436,-2.114,...,0.136,0.109,-0.615,0.327,-4.627,-4.789,-5.101,-2.608,-3.508,0.175
1,0.968,0.437,0.066,0.566,0.194,-0.893,-1.566,-2.360,0.332,-2.114,...,-0.128,0.124,0.032,0.600,-0.843,0.160,0.364,-0.335,-0.730,0.676
2,1.013,0.568,0.235,0.370,0.112,-0.797,-1.367,-2.360,0.396,-2.114,...,-0.009,0.361,0.277,-0.116,-0.843,0.160,0.364,0.765,-0.589,0.633
3,0.733,0.368,0.283,0.165,0.599,-0.679,-1.200,-2.086,0.403,-2.114,...,0.015,0.417,0.279,0.603,-0.843,-0.065,0.364,0.333,-0.112,0.206
4,0.684,0.638,0.260,0.209,0.337,-0.454,-1.073,-2.086,0.314,-2.114,...,0.183,1.078,0.328,0.418,-0.843,-0.215,0.364,-0.280,-0.028,0.384
5,0.445,0.627,0.408,0.220,0.458,-1.056,-1.009,-1.896,0.481,-2.114,...,0.454,0.674,0.358,0.618,-0.843,-0.290,0.364,-0.191,-0.883,0.060
6,0.889,0.416,0.640,0.356,0.224,-0.893,-0.812,-1.823,0.729,-2.114,...,0.454,0.081,0.243,0.468,-0.843,-0.290,0.364,-0.155,-1.318,0.415
7,0.984,0.529,0.704,0.438,0.258,-0.917,-0.682,-1.721,0.753,-2.114,...,0.139,-0.050,0.428,-0.119,-0.843,-0.290,0.364,0.100,-0.899,0.609
8,0.948,0.850,0.584,0.459,0.591,-0.523,-0.591,-1.524,0.763,-2.114,...,0.188,0.467,0.597,-0.057,-0.843,-0.290,0.364,0.053,-0.553,0.981
9,1.157,1.055,0.638,0.617,1.483,-0.731,-0.612,-1.524,0.968,-2.114,...,0.860,0.456,0.916,0.039,-0.843,-0.290,0.364,0.151,-1.157,0.818
10,1.116,1.112,0.612,0.639,0.919,-0.895,-0.656,-1.418,0.891,-2.114,...,0.860,-0.097,0.795,-0.452,-0.843,-0.290,0.364,-0.054,-0.426,0.877
11,1.093,1.120,0.522,0.797,0.953,-0.619,-0.591,-1.390,1.044,-2.114,...,1.654,0.755,0.903,-0.627,-0.843,-2.315,-0.289,-0.054,0.079,1.077
12,-0.632,-0.959,-0.474,1.194,-0.170,-0.572,-0.779,-1.350,-1.034,-2.114,...,1.873,-0.613,-0.949,-0.716,-0.843,-2.315,-0.289,0.410,1.837,-1.099
13,-0.999,-1.343,-0.454,1.156,-0.523,-0.786,-0.988,-1.463,-1.948,-2.114,...,1.873,0.023,-1.803,-0.512,-0.441,-0.918,-0.943,-0.737,1.314,-1.656
14,-0.234,-0.248,-0.271,0.940,0.174,-0.610,-1.102,-1.463,-0.987,-2.114,...,2.002,-0.132,-0.897,-0.170,-0.862,-1.063,-1.388,-1.230,0.940,-0.615
15,-0.898,-1.057,-0.655,0.940,-0.544,-0.654,-1.245,-1.634,-1.784,-2.114,...,1.935,0.466,-1.566,0.264,-0.900,-1.134,-1.537,0.049,1.681,-1.366
16,-0.403,-0.486,-0.304,0.951,-0.294,-0.488,-1.290,-1.686,-1.105,-2.114,...,1.887,1.369,-1.133,0.450,-1.760,-0.852,-2.131,-1.411,0.747,-0.345
17,-1.158,-1.538,-0.585,0.797,-0.818,-0.668,-1.416,-1.759,-2.330,-2.114,...,1.212,0.174,-2.111,0.390,-1.760,-0.852,-2.131,-0.131,1.019,-1.625
18,-0.638,-0.312,-0.059,0.831,-0.223,-0.907,-1.403,-1.878,-1.317,-2.114,...,0.834,0.194,-1.006,1.002,-1.760,-0.852,-2.131,-1.140,0.003,-0.735
19,0.375,0.422,0.369,0.929,0.132,-1.599,-1.263,-1.878,-0.323,-2.114,...,0.163,-0.123,-0.342,0.913,-0.613,-0.571,-0.943,-0.891,-0.536,-0.153
20,0.211,0.385,0.491,1.182,-0.035,-1.287,-1.127,-1.840,-0.612,-2.114,...,0.131,-0.574,-0.363,0.170,-0.613,-0.548,-0.943,-0.084,-0.780,0.054
21,-0.041,0.093,0.354,1.264,-0.221,-1.078,-1.028,-1.801,-0.749,-2.114,...,-0.225,-0.564,-0.456,-0.524,3.171,2.635,-1.596,0.267,-0.123,0.037
22,0.369,0.479,0.723,1.360,0.072,-0.747,-0.888,-1.746,0.099,-2.114,...,-0.405,-0.861,-0.058,-0.894,3.802,1.173,-0.943,-0.474,-0.824,0.295
23,-0.143,-0.345,0.363,1.313,0.040,-0.516,-0.754,-1.617,-0.643,-2.114,...,-0.405,-0.901,-0.467,-0.957,4.731,3.872,-0.943,-0.120,0.311,0.064
24,-2.028,-2.665,-0.467,0.435,-1.479,-0.562,-0.798,-1.617,-2.754,-2.114,...,0.114,-0.636,-2.632,-0.988,2.483,1.416,-0.289,1.959,1.796,-2.586
25,-1.692,-2.180,-0.595,-0.669,-0.854,-0.574,-0.899,-1.610,-2.546,-2.114,...,0.152,-0.197,-2.397,-0.907,1.107,0.385,-0.289,-1.239,1.484,-2.613
26,0.618,0.245,0.382,-0.131,0.966,-1.081,-0.892,-1.640,0.291,-2.114,...,0.568,0.332,-0.252,0.033,0.820,0.554,-0.289,-2.565,-0.957,-0.073
27,1.196,1.166,0.748,-0.596,1.421,-1.184,-0.808,-1.682,0.587,-2.114,...,1.095,2.050,0.700,1.204,0.534,1.416,0.310,-1.918,-1.106,1.273
28,1.106,1.177,1.033,-0.045,1.124,-1.814,-0.490,-1.549,0.544,-2.114,...,1.329,-0.102,0.668,-0.080,0.820,1.454,0.364,0.088,-1.030,1.849
29,0.462,0.480,0.593,-0.319,0.333,-1.293,-0.382,-1.549,-0.160,-2.114,...,1.027,-0.285,0.079,-0.727,-0.135,0.043,0.364,2.010,-0.164,0.718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2858,0.430,0.225,-0.893,-0.803,0.490,0.131,-0.610,-0.388,0.063,0.042,...,1.517,-2.440,0.318,-2.285,-4.627,-4.789,0.364,0.083,1.578,-0.258
2859,0.425,0.343,-0.725,-0.803,0.515,-0.069,-0.658,-0.411,0.031,0.042,...,1.754,0.242,0.206,-0.838,-2.620,-2.821,0.720,-0.444,1.112,-0.194
2860,0.815,0.932,0.101,-0.655,0.955,-0.568,-0.534,-0.437,0.648,0.329,...,1.621,0.368,0.199,-0.331,-1.784,-2.001,0.720,-0.648,-0.509,0.104
2861,0.872,0.872,0.114,-0.477,0.688,0.135,-0.317,-0.437,0.783,0.473,...,1.127,0.875,0.468,-0.226,-0.116,-0.121,0.720,-0.256,0.009,0.418
2862,0.161,0.362,-0.631,0.028,0.302,0.156,-0.280,-0.324,-0.164,0.473,...,0.746,-0.360,0.689,-0.475,-0.652,-0.834,0.720,1.084,1.496,0.204
2863,-0.927,-0.998,-0.838,0.145,-0.299,0.064,-0.407,-0.324,-1.369,0.473,...,0.745,0.294,-0.334,-0.425,-0.040,-2.540,0.839,0.221,1.021,0.303
2864,-0.024,0.348,-0.255,0.147,0.061,-0.105,-0.390,-0.316,-0.342,0.473,...,0.743,-0.298,-0.171,0.606,-0.040,-2.540,0.839,-0.094,0.260,0.766
2865,-0.993,-1.132,-0.841,0.070,0.090,-0.083,-0.333,-0.300,-1.249,0.473,...,0.589,0.050,-0.228,0.186,-0.040,-0.290,0.839,0.827,1.375,-0.409
2866,-0.433,-0.544,-0.866,-0.480,0.459,0.034,-0.370,-0.335,-0.767,0.473,...,0.589,-0.115,-0.529,0.036,0.056,-0.196,0.839,0.029,1.225,-0.766
2867,0.319,0.164,-0.207,-0.692,0.312,-0.013,-0.354,-0.335,0.070,0.473,...,0.453,0.071,-0.559,0.269,0.648,0.385,0.839,-0.724,-0.377,-0.189
2868,0.296,0.477,-0.417,-0.828,0.212,-0.133,-0.306,-0.357,0.050,0.473,...,0.139,1.830,0.194,1.350,0.304,0.160,0.839,-1.033,0.404,-0.099
2869,0.490,0.497,-0.043,-0.828,0.245,-0.324,-0.193,-0.298,0.243,0.473,...,0.139,0.327,0.336,0.806,0.648,0.160,0.839,-0.116,-0.649,0.012
2870,0.446,0.240,0.727,-0.656,-0.272,-0.227,0.045,-0.298,0.231,0.473,...,-0.206,1.327,0.325,1.484,-0.040,-0.355,0.839,-0.016,-1.318,0.249
2871,0.494,0.640,0.339,-0.221,0.149,-0.181,0.159,-0.160,0.241,0.473,...,-0.666,0.763,0.436,1.143,-0.040,-0.346,0.839,0.339,-0.517,0.342
2872,0.173,0.074,0.843,-0.017,-0.733,-0.105,0.348,-0.008,0.384,0.904,...,-0.781,1.002,0.456,0.999,-0.438,-0.754,0.547,0.218,-1.319,0.224
2873,-0.417,0.096,-0.129,-0.028,-1.104,0.072,0.336,0.051,-0.154,0.904,...,-1.351,1.452,0.352,0.809,-0.470,-0.726,0.423,0.215,0.158,-0.031
2874,0.375,0.595,0.177,0.011,-0.527,-0.112,0.342,0.062,0.437,0.904,...,-1.249,-0.202,0.396,-0.064,0.304,0.160,0.364,-0.303,-0.439,0.579
2875,-0.765,-0.023,0.434,-0.045,-1.408,0.372,0.524,0.171,0.348,0.904,...,-1.453,1.036,0.381,1.993,0.304,-0.065,-0.156,0.372,0.257,0.081
2876,-0.704,0.246,-0.078,-0.131,-0.630,0.004,0.466,0.195,-0.016,0.904,...,-1.475,0.195,0.381,0.646,0.304,0.273,-0.230,-0.207,-0.112,0.539
2877,0.041,0.459,0.460,-0.185,-0.421,0.195,0.544,0.219,0.679,0.904,...,-1.423,0.730,0.487,0.368,0.017,-0.290,-0.349,0.177,-0.537,0.565
2878,0.363,0.650,0.315,-0.148,-0.374,-0.072,0.619,0.336,0.631,0.904,...,-1.267,-0.135,0.575,0.582,0.017,-0.290,-0.349,0.051,-0.136,0.709
2879,0.666,0.801,0.459,-0.107,0.125,-0.073,0.690,0.336,0.863,0.904,...,-1.109,0.607,0.697,1.128,-0.040,-0.290,-0.349,-0.087,0.049,0.917
2880,0.621,0.685,0.162,-0.078,0.625,-0.117,0.658,0.437,0.580,0.904,...,-0.693,0.366,0.839,1.297,-0.040,-0.290,-0.349,0.359,-0.276,0.682
2881,0.950,0.889,0.340,0.006,0.417,-0.083,0.739,0.474,1.090,0.904,...,-0.174,0.644,0.839,0.485,-0.040,-0.290,-0.349,-0.038,0.149,0.892
2882,0.698,0.812,0.169,0.125,0.580,0.057,0.781,0.511,0.866,0.904,...,-0.174,0.307,0.902,0.257,-0.040,-0.290,-0.349,0.407,0.230,0.812
2883,0.190,-0.025,-0.138,0.161,0.600,-0.212,0.757,0.584,-0.026,0.904,...,0.128,-0.208,0.809,-0.173,0.247,-0.027,-0.349,0.576,0.686,0.235
2884,0.507,0.557,0.296,0.183,0.530,-0.237,0.749,0.584,0.537,0.904,...,0.291,-0.287,0.465,-0.310,0.763,0.498,-0.349,-0.615,-0.380,1.042
2885,-0.394,-0.721,-0.485,0.084,0.136,0.034,0.655,0.614,-0.818,0.904,...,0.291,-0.179,0.268,0.552,0.763,0.498,-0.349,0.951,0.748,0.005
2886,-0.219,-0.282,-0.344,-0.049,0.449,-0.140,0.560,0.583,-0.596,0.904,...,0.216,1.061,-0.051,1.023,0.878,0.610,-0.230,-0.301,0.555,0.350
2887,0.368,0.380,-0.225,-0.049,0.379,0.092,0.550,0.551,0.244,0.904,...,0.047,0.057,-0.042,0.847,0.534,-0.009,-0.190,-0.567,0.388,0.417

In [5]:
for i in table.head().index:
    print(i)

0
1
2
3
4

# 类型转换

In [ ]:
#把所有 bool 转int
for u in issame_pd.columns:
    if issame_pd[u].dtype==bool:
        issame_pd[u]=issame_pd[u].astype('int')

# 选取行列

In [ ]:
table.iloc[:,:38].head()  # 所有行，前38列

# 添加行列  [cankao](https://blog.csdn.net/claroja/article/details/65661826)

In [6]:
import numpy as np

df=pd.DataFrame(np.arange(16).reshape((4,4)),index=['a','b','c','d'],columns=['one','two','three','four']) 
df

   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [9]:
#行
df.loc["new"]='3'
df.loc[0]='4'
#列
df['column']="a"
df

    one two three four column
a     0   1     2    3      a
b     4   5     6    7      a
c     8   9    10   11      a
d    12  13    14   15      a
new   3   3     3    3      a
0     4   4     4    4      a

## 插入或更改一行

In [15]:
# 修改列名
df.columns=[1,2,3,4,5]
df

#插入
# 切割+拼接

      1   2   3   4  5
a     0   1   2   3  1
b     4   5   6   7  2
c     8   9  10  11  3
d    12  13  14  15  4
new   2   2   2   2  5

# 表格创建和并列

In [14]:
import pandas as pd
df1=pd.Series(range(7))
print(df1)
result = pd.concat([df1, df1], axis=1)
print(result)
saveCsv=pd.DataFrame( result)
saveCsv.to_csv("tagData.csv", index=True, sep=',')

0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64
   0  1
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4
5  5  5
6  6  6

# 写数组到CSV

In [7]:

import random
import time
import pandas as pd
import numpy as np
tagData=np.array(range(16)).reshape(4,4)
#tagData=np.array(["2",3,"d"])
saveCsv=pd.DataFrame( tagData)
saveCsv.to_csv("tagData.csv", index=True, sep=',')

# 写字典数组 到csv

In [1]:

import random
import time
import pandas as pd
Len=10
tagData=[{"d1":1,"d2":2,"d3":3}]

dataMapD1=[random.choice("ab") for i in range(Len)]
dataMapD2=[random.uniform(time.time()-1000,time.time()+1000) for i in range(Len)]
dataMapD3=[(random.uniform(116.403406-10,116.403406+10),random.uniform(39.914935-10,39.914935+10)) for i in range(Len)]
tagData=({"d1":i,"d2":j,"d3":k} for i ,j,k in zip(dataMapD1,dataMapD2,dataMapD3))


saveCsv=pd.DataFrame( tagData)
saveCsv.to_csv("tagData.csv", index=False, sep=',',mode="a")  #mode 默认为w 所以要增加改成a
saveCsv
# 创建数据
df1=saveCsv

  d1            d2                                        d3
0  a  1.550325e+09   (112.61648455091895, 48.24510351539536)
1  a  1.550326e+09  (125.63563526037134, 45.647453732492174)
2  a  1.550325e+09  (113.80341203154198, 30.330302386391537)
3  a  1.550325e+09   (114.83991747334863, 36.66843078397682)
4  b  1.550325e+09    (110.0978111589435, 41.77628925736187)
5  a  1.550325e+09  (121.28960945839927, 40.190492008877044)
6  b  1.550325e+09   (111.56313691394332, 44.58197626509966)
7  b  1.550326e+09  (111.94077315163997, 32.779725727490316)
8  b  1.550325e+09    (124.20786448412936, 39.7568303740563)
9  a  1.550326e+09  (118.77618164938188, 30.927877650662907)

# groupby
返回一个 df 对象里面是

返回一个元组  0 是 group 的值  1 是df 对象的所有行

In [ ]:
# 分类求和
df1=base_data.groupby(['d1,'d2']['',''].sum()

In [81]:


grouped = df1.groupby('d1')
# for i in grouped:
#     print(i[0])
# for i in grouped:
#     print(i[1]["d1"])
    
for i,j in grouped:
    print(i)
    print(j)
    print("+++++++++++++++++++++++++")
    print("len",len(j))
   # print(j+j)
    print(j[["d1","d2"]][:3])
    print(grouped.size()[i])
    print("+++++++++++++++++++++++++")
    
#len ( (i for i in range(10)))

a
  d1            d2                                        d3
0  a  1.546831e+09  (110.47443455334906, 37.976946655571375)
1  a  1.546831e+09  (117.35809701401953, 44.339268945341445)
3  a  1.546831e+09   (123.6241511063321, 29.944813464705298)
4  a  1.546830e+09  (113.65009482429744, 48.196519288305694)
6  a  1.546831e+09   (123.83172209314667, 49.50732161311943)
7  a  1.546830e+09   (116.4717783848038, 37.747542049089034)
9  a  1.546831e+09   (116.44486713663488, 34.60986795139405)
+++++++++++++++++++++++++
len 7
   d1            d2                                                 d3
0  aa  3.093662e+09  (110.47443455334906, 37.976946655571375, 110.4...
1  aa  3.093663e+09  (117.35809701401953, 44.339268945341445, 117.3...
3  aa  3.093662e+09  (123.6241511063321, 29.944813464705298, 123.62...
4  aa  3.093661e+09  (113.65009482429744, 48.196519288305694, 113.6...
6  aa  3.093662e+09  (123.83172209314667, 49.50732161311943, 123.83...
7  aa  3.093660e+09  (116.4717783848038, 37.747542049089034, 116.47...
9  aa  3.093661e+09  (116.44486713663488, 34.60986795139405, 116.44...
  d1            d2
0  a  1.546831e+09
1  a  1.546831e+09
3  a  1.546831e+09
7
+++++++++++++++++++++++++
b
  d1            d2                                        d3
2  b  1.546831e+09   (107.26861396143475, 47.70697641278318)
5  b  1.546831e+09   (109.34629322675231, 36.71393760005099)
8  b  1.546831e+09  (124.20441606260636, 42.914865961407415)
+++++++++++++++++++++++++
len 3
   d1            d2                                                 d3
2  bb  3.093662e+09  (107.26861396143475, 47.70697641278318, 107.26...
5  bb  3.093662e+09  (109.34629322675231, 36.71393760005099, 109.34...
8  bb  3.093663e+09  (124.20441606260636, 42.914865961407415, 124.2...
  d1            d2
2  b  1.546831e+09
5  b  1.546831e+09
8  b  1.546831e+09
3
+++++++++++++++++++++++++

In [122]:
# 数量大于n 的分组
t=[j for i,j in grouped if grouped.size()[i] >2]

t=[i[["d1","d2"]] [:4] for i  in t]
#t[["d1","d2"]] [:4] cuowu
for i in t :
    print(i.to_dict())
for i in t:

    for j,k in i.items() :
        print("==========")
        #print(j,k)
        print( [{j:l} for l in k])

{'d1': {0: 'a', 1: 'a', 3: 'a', 4: 'a'}, 'd2': {0: 1546830971.9024727, 1: 1546831295.3482182, 3: 1546830871.0391097, 4: 1546830269.3660083}}
{'d1': {2: 'b', 5: 'b', 8: 'b'}, 'd2': {2: 1546831109.5617502, 5: 1546830787.821706, 8: 1546831427.975249}}
==========
[{'d1': 'a'}, {'d1': 'a'}, {'d1': 'a'}, {'d1': 'a'}]
==========
[{'d2': 1546830971.9024727}, {'d2': 1546831295.3482182}, {'d2': 1546830871.0391097}, {'d2': 1546830269.3660083}]
==========
[{'d1': 'b'}, {'d1': 'b'}, {'d1': 'b'}]
==========
[{'d2': 1546831109.5617502}, {'d2': 1546830787.821706}, {'d2': 1546831427.975249}]

In [222]:
a=[(2, 3), (3, 4), (4, 1), (1, 3)]
a.sort(key=lambda x:x[1])

random = [(2, 3), (3, 4), (4, 1), (1, 3)]
 
grouped=pd.DataFrame(random)
print(grouped,"\n===========")

grouped=grouped.groupby(1)
for g,i in grouped:
    print(i,'\n')
print("============")
l=[]
t=(each_df[0][:1] for g,each_df in grouped)
for i in t:
    l+=list(i)

for g,each_df in grouped:
   l+=list(each_df[0][:1])
import numpy as np
np.array(random)[:,1].tolist()

   0  1
0  2  3
1  3  4
2  4  1
3  1  3
===========
   0  1
2  4  1

   0  1
0  2  3
3  1  3

   0  1
1  3  4

============

array([3, 4, 1, 3])

# 读取csv

In [8]:
#data =pd.read_csv(r"C:\Users\user\OneDrive\code space\python\1notebook\data\tagData.csv")
data=pd.read_csv("tagData.csv")
data

,d1,d2,d3
0,0.9125409867491918,1543559382.162108,"(123.67377525379733, 46.84945879931765)"
1,0.20120199889569151,1543560741.8527527,"(110.7636576966396, 38.677861353844634)"
2,0.35819917782116384,1543560836.3228948,"(121.33518800185773, 31.348482401326084)"
3,0.459336715845037,1543560560.200682,"(108.31435841638127, 48.784513943766896)"
4,0.8448210745857367,1543561105.9062188,"(111.99258513743678, 39.97270150135577)"
5,0.9148433381655829,1543559894.4326143,"(119.69937265277574, 47.32751636185243)"
6,0.5633268202060597,1543559269.1755526,"(120.68398382433318, 37.23511331828462)"
7,0.8957732169983896,1543559575.4414225,"(124.0580411176716, 48.666463306075634)"
8,0.407338217020962,1543560087.4648385,"(110.14492185361212, 47.691968704791094)"
9,0.6265109352938901,1543560008.4113736,"(112.5717673588419, 33.11247338533024)"
10,d1,d2,d3
11,0.5160130750829113,1543560852.8909962,"(114.01922869797099, 30.326967185332)"
12,0.43173371283753526,1543560431.7439637,"(111.40028521866361, 44.537465185669824)"
13,0.3398520160117585,1543560270.2508895,"(121.9929394829491, 43.06986431033084)"
14,0.49472952698026756,1543560732.6628125,"(114.54381519878336, 33.25648358139442)"
15,0.8337472601525879,1543560731.0176609,"(107.38787617125722, 45.051043458192396)"
16,0.24140995270115617,1543559915.9692078,"(109.0528017871154, 40.54291511405441)"
17,0.8867501839118266,1543559743.612194,"(107.89709108721794, 37.78577730741819)"
18,0.474686189829152,1543559494.7214766,"(118.19874737232234, 30.037273083650824)"
19,0.9412656074388821,1543559320.4349597,"(125.66381404548581, 38.50071524031779)"
20,0.4819513056722715,1543560722.9567559,"(124.5805987035731, 42.88244301626382)"

In [ ]:
saveCsv.hand()  头几行数据

# 读取数据库

In [2]:
# mysql
import pandas as pd
import pymysql 
db = pymysql.connect(host='localhost',port=3306,user='root',passwd='123456',charset='UTF8',db='id_info_cahe_copy') 
cur = db.cursor() 

sql="""SELECT
id_info.idcard,
id_info.nation,
id_info.`name`,
id_info.sex,
id_info.memo,
id_info.avatar,
id_info.create_datetime,
id_info.image_path,
id_info.id
FROM
id_info
WHERE
id_info.`name` like "王飞" """
df=pd.read_sql(sql,con=db)
cur.execute(sql)
print(df)

               idcard nation name sex  memo avatar     create_datetime  \
0  652923199002201816     汉族   王飞   男  null   None 2018-09-06 15:39:50
1  653122198809204416     汉族   王飞   男  null   None 2018-09-06 16:34:29
2  652924198910120546     汉族   王飞   女  null   None 2018-09-06 19:48:02
3  652324198210212818     汉族   王飞   男  null   None 2018-09-07 10:23:04

                                          image_path     id
0  /app/id_img/cb0/2ec/cb02ecb6-00b9-4839-9cd3-c2...  23719
1  /app/id_img/0a6/224/0a622493-5a6e-48bb-a1e9-fa...  27973
2  /app/id_img/afb/ada/afbada74-8fc2-4900-914b-ca...  37914
3  /app/id_img/db8/378/db8378ab-826d-44df-a6a7-58...  40541

# 合并 查询

In [1]:
# 纵向合并 

res = df.append([df2, df3], ignore_index=True)
print(res)

NameError: name 'df' is not defined

In [6]:
#表格操作，

# 知道列名 使用df.loc
print( df.loc[:,["idcard","image_path"]])
#不知道列名 使用  df.iloc
print( df.iloc[:,[1,2]])

# pd转num array
print(df.values)

               idcard                                         image_path
0  652923199002201816  /app/id_img/cb0/2ec/cb02ecb6-00b9-4839-9cd3-c2...
1  653122198809204416  /app/id_img/0a6/224/0a622493-5a6e-48bb-a1e9-fa...
2  652924198910120546  /app/id_img/afb/ada/afbada74-8fc2-4900-914b-ca...
3  652324198210212818  /app/id_img/db8/378/db8378ab-826d-44df-a6a7-58...
  nation name
0     汉族   王飞
1     汉族   王飞
2     汉族   王飞
3     汉族   王飞

array([['652923199002201816', '汉族', '王飞', '男', 'null', None,
        Timestamp('2018-09-06 15:39:50'),
        '/app/id_img/cb0/2ec/cb02ecb6-00b9-4839-9cd3-c29df9d1ae63.jpg',
        23719],
       ['653122198809204416', '汉族', '王飞', '男', 'null', None,
        Timestamp('2018-09-06 16:34:29'),
        '/app/id_img/0a6/224/0a622493-5a6e-48bb-a1e9-fa81983f6ad2.jpg',
        27973],
       ['652924198910120546', '汉族', '王飞', '女', 'null', None,
        Timestamp('2018-09-06 19:48:02'),
        '/app/id_img/afb/ada/afbada74-8fc2-4900-914b-cac377fea242.jpg',
        37914],
       ['652324198210212818', '汉族', '王飞', '男', 'null', None,
        Timestamp('2018-09-07 10:23:04'),
        '/app/id_img/db8/378/db8378ab-826d-44df-a6a7-58b5520d6617.jpg',
        40541]], dtype=object)

In [93]:
import pymysql
database={
            # 本地配置
            'USER': 'root',
            'PASSWORD': '123456',
            'HOST': "localhost",
            'ENGINE': 'django.db.backends.mysql',
            'NAME': "test",
            'PORT':3306
        }


db=pymysql.connect(database["HOST"], database["USER"], database["PASSWORD"], database["NAME"],
                                  port=int(database["PORT"]))
id=("111","1234")
uri="2222saffa"
i=124
sql = f"INSERT INTO yt_id_uri(image_id, uri,a)VALUES ('{id}','{uri}',{i})"  

sql = f"DELETE FROM yt_id_uri WHERE image_id='{id}'"
sql = f"SELECT uri FROM yt_id_uri WHERE image_id in ('111','1234','223')"
sql = f"SELECT uri FROM yt_id_uri WHERE image_id in {id}"
cur = db.cursor()
cur.execute(sql)

r=cur.fetchone()
rr=cur.fetchall()

db.commit()
for i in rr:
    print(i)

('21412',)
('3',)
(None,)